name: Basic Workflow - Manual Trigger

on:
  workflow_dispatch:
    inputs:
      ## name of variable
      environment:
        ## Simple description
        description: 'The environment to deploy to'
        required: true
        ## optional param
        default: 'production'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy
        run: echo "Deploying to ${{ github.event.inputs.environment }} environment"
