name: Basic Workflow - Pull Request Trigger

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Running unit tests
        run: echo "Runing unit tests on pull request event"
